/** 一般銀行振込_三菱UFJ */
const GENERAL_BANK_TRANSFER_MITSUBISHI_UFJ = 10

/** 一般銀行振込_ジャパンネット */
const GENERAL_BANK_TRANSFER_JAPAN_NET = 20

/** 一般銀行振込_三菱UFJ銀行_おまかせバンク */
const GENERAL_BANK_TRANSFER_MITSUBISHI_UFJ_BANK_OMAKASE_BANK = 30

/** 一般銀行振込_みずほ銀行 */
const GENERAL_BANK_TRANSFER_MIZUHO_BANK = 35

/** 楽天銀行振込 */
const RAKUTEN_BANK_TRANSFER = 80

/** ビッタズ銀行振込_ジャパンネット */
const BITAZU_BANK_TRANSFER_JAPAN_NET = 105

/** 卸銀行振込_三菱UFJ銀行 */
const WHOLESALE_BANK_TRANSFER_MITSUBISHI_UFJ_BANK = 140

/** 卸銀行振込_ジャパンネット */
const WHOLESALE_BANK_TRANSFER_JAPAN_NET = 150

/** Yahoo銀行振込 */
const YAHOO_BANK_TRANSFER = 250

/** 酒_楽天銀行振込 */
const SAKE_RAKUTEN_BANK_TRANSFER = 330

/** 酒_Yahoo銀行振込 */
const SAKE_YAHOO_BANK_TRANSFER = 410

/** ポンパレ銀行振込 */
const PONPALLET_BANK_TRANSFER = 610

/** 楽天ペイ銀行振込 */
const RAKUTEN_PAY_BANK_TRANSFER = 907

/** 酒_楽天ペイ銀行振込 */
const SAKE_RAKUTEN_PAY_BANK_TRANSFER = 927

export const BANK_TRANSFER = [
  GENERAL_BANK_TRANSFER_MITSUBISHI_UFJ,
  GENERAL_BANK_TRANSFER_JAPAN_NET,
  GENERAL_BANK_TRANSFER_MITSUBISHI_UFJ_BANK_OMAKASE_BANK,
  GENERAL_BANK_TRANSFER_MIZUHO_BANK,
  RAKUTEN_BANK_TRANSFER,
  BITAZU_BANK_TRANSFER_JAPAN_NET,
  WHOLESALE_BANK_TRANSFER_MITSUBISHI_UFJ_BANK,
  WHOLESALE_BANK_TRANSFER_JAPAN_NET,
  YAHOO_BANK_TRANSFER,
  SAKE_RAKUTEN_BANK_TRANSFER,
  SAKE_YAHOO_BANK_TRANSFER,
  PONPALLET_BANK_TRANSFER,
  RAKUTEN_PAY_BANK_TRANSFER,
  SAKE_RAKUTEN_PAY_BANK_TRANSFER
]
